spring:
  profiles:
    active: dev



---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/recruitment
    username: root
    password: 2575824162
server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #  config-location: classpath:mapper-config.xml
  configuration:
    map-underscore-to-camel-case: true

